// country code list with all country name, country code, two letter code, and flag based on https://en.wikipedia.org/wiki/List_of_country_calling_codes
import { CountryId } from '../enum/CountryIds';

export interface CountryCode {
  code: string; // e.g. '+1'
  id: CountryId; // e.g. CountryId.UNITED_STATES
  flag: string; // e.g. '🇺🇸'
  name: string; // e.g. 'United States'
  mask: string; // e.g. '(###)-###-####'
}


export const countryCodeList: CountryCode[] = [
    // Zone 1 - North American Numbering Plan (NANP)
    { code: '+1', id: CountryId.UNITED_STATES, flag: '🇺🇸', name: 'United States', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.CANADA, flag: '🇨🇦', name: 'Canada', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.ANTIGUA_AND_BARBUDA, flag: '🇦🇬', name: 'Antigua and Barbuda', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.ANGUILLA, flag: '🇦🇮', name: 'Anguilla', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.AMERICAN_SAMOA, flag: '🇦🇸', name: 'American Samoa', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.BAHAMAS, flag: '🇧🇸', name: 'Bahamas', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.BARBADOS, flag: '🇧🇧', name: 'Barbados', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.BERMUDA, flag: '🇧🇲', name: 'Bermuda', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.BRITISH_VIRGIN_ISLANDS, flag: '🇻🇬', name: 'British Virgin Islands', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.CAYMAN_ISLANDS, flag: '🇰🇾', name: 'Cayman Islands', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.DOMINICA, flag: '🇩🇲', name: 'Dominica', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.DOMINICAN_REPUBLIC, flag: '🇩🇴', name: 'Dominican Republic', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.GRENADA, flag: '🇬🇩', name: 'Grenada', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.GUAM, flag: '🇬🇺', name: 'Guam', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.JAMAICA, flag: '🇯🇲', name: 'Jamaica', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.MONTSERRAT, flag: '🇲🇸', name: 'Montserrat', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.NORTHERN_MARIANA_ISLANDS, flag: '🇲🇵', name: 'Northern Mariana Islands', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.PUERTO_RICO, flag: '🇵🇷', name: 'Puerto Rico', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.SAINT_KITTS_AND_NEVIS, flag: '🇰🇳', name: 'Saint Kitts and Nevis', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.SAINT_LUCIA, flag: '🇱🇨', name: 'Saint Lucia', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.SAINT_VINCENT_AND_THE_GRENADINES, flag: '🇻🇨', name: 'Saint Vincent and the Grenadines', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.SINT_MAARTEN, flag: '🇸🇽', name: 'Sint Maarten', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.TRINIDAD_AND_TOBAGO, flag: '🇹🇹', name: 'Trinidad and Tobago', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.TURKS_AND_CAICOS_ISLANDS, flag: '🇹🇨', name: 'Turks and Caicos Islands', mask: '(###)-###-####' },
    { code: '+1', id: CountryId.UNITED_STATES_VIRGIN_ISLANDS, flag: '🇻🇮', name: 'United States Virgin Islands', mask: '(###)-###-####' },
    // Zone 2 - Africa
    { code: '+20', id: CountryId.EGYPT, flag: '🇪🇬', name: 'Egypt', mask: '(###)-###-####' },
    { code: '+211', id: CountryId.SOUTH_SUDAN, flag: '🇸🇸', name: 'South Sudan', mask: '(###)-###-###' },
    { code: '+212', id: CountryId.MOROCCO, flag: '🇲🇦', name: 'Morocco', mask: '(###)-###-###' },
    { code: '+212', id: CountryId.WESTERN_SAHARA, flag: '🇪🇭', name: 'Western Sahara', mask: '(###)-###-###' },
    { code: '+213', id: CountryId.ALGERIA, flag: '🇩🇿', name: 'Algeria', mask: '(###)-##-##-##' },
    { code: '+216', id: CountryId.TUNISIA, flag: '🇹🇳', name: 'Tunisia', mask: '(##)-###-###' },
    { code: '+218', id: CountryId.LIBYA, flag: '🇱🇾', name: 'Libya', mask: '(##)-#######' },
    { code: '+220', id: CountryId.GAMBIA, flag: '🇬🇲', name: 'Gambia', mask: '(###)-####' },
    { code: '+221', id: CountryId.SENEGAL, flag: '🇸🇳', name: 'Senegal', mask: '(##)-###-##-##' },
    { code: '+222', id: CountryId.MAURITANIA, flag: '🇲🇷', name: 'Mauritania', mask: '(##)-##-##-##' },
    { code: '+223', id: CountryId.MALI, flag: '🇲🇱', name: 'Mali', mask: '(##)-##-##-##' },
    { code: '+224', id: CountryId.GUINEA, flag: '🇬🇳', name: 'Guinea', mask: '(###)-##-##-##' },
    { code: '+225', id: CountryId.IVORY_COAST, flag: '🇨🇮', name: 'Ivory Coast', mask: '(##)-##-##-##' },
    { code: '+226', id: CountryId.BURKINA_FASO, flag: '🇧🇫', name: 'Burkina Faso', mask: '(##)-##-##-##' },
    { code: '+227', id: CountryId.NIGER, flag: '🇳🇪', name: 'Niger', mask: '(##)-##-##-##' },
    { code: '+228', id: CountryId.TOGO, flag: '🇹🇬', name: 'Togo', mask: '(##)-##-##-##' },
    { code: '+229', id: CountryId.BENIN, flag: '🇧🇯', name: 'Benin', mask: '(##)-##-##-##' },
    { code: '+230', id: CountryId.MAURITIUS, flag: '🇲🇺', name: 'Mauritius', mask: '(####)-####' },
    { code: '+231', id: CountryId.LIBERIA, flag: '🇱🇷', name: 'Liberia', mask: '(###)-####' },
    { code: '+232', id: CountryId.SIERRA_LEONE, flag: '🇸🇱', name: 'Sierra Leone', mask: '(##)-######' },
    { code: '+233', id: CountryId.GHANA, flag: '🇬🇭', name: 'Ghana', mask: '(##)-###-####' },
    { code: '+234', id: CountryId.NIGERIA, flag: '🇳🇬', name: 'Nigeria', mask: '(###)-###-####' },
    { code: '+235', id: CountryId.CHAD, flag: '🇹🇩', name: 'Chad', mask: '(##)-##-##-##' },
    { code: '+236', id: CountryId.CENTRAL_AFRICAN_REPUBLIC, flag: '🇨🇫', name: 'Central African Republic', mask: '(##)-##-##-##' },
    { code: '+237', id: CountryId.CAMEROON, flag: '🇨🇲', name: 'Cameroon', mask: '(##)-##-##-##' },
    { code: '+238', id: CountryId.CAPE_VERDE, flag: '🇨🇻', name: 'Cape Verde', mask: '(###)-##-##' },
    { code: '+239', id: CountryId.SAO_TOME_AND_PRINCIPE, flag: '🇸🇹', name: 'São Tomé and Príncipe', mask: '(###)-####' },
    { code: '+240', id: CountryId.EQUATORIAL_GUINEA, flag: '🇬🇶', name: 'Equatorial Guinea', mask: '(###)-###-###' },
    { code: '+241', id: CountryId.GABON, flag: '🇬🇦', name: 'Gabon', mask: '(##)-##-##-##' },
    { code: '+242', id: CountryId.REPUBLIC_OF_THE_CONGO, flag: '🇨🇬', name: 'Republic of the Congo', mask: '(##)-###-####' },
    { code: '+243', id: CountryId.DEMOCRATIC_REPUBLIC_OF_THE_CONGO, flag: '🇨🇩', name: 'Democratic Republic of the Congo', mask: '(###)-###-###' },
    { code: '+244', id: CountryId.ANGOLA, flag: '🇦🇴', name: 'Angola', mask: '(###)-###-###' },
    { code: '+245', id: CountryId.GUINEA_BISSAU, flag: '🇬🇼', name: 'Guinea-Bissau', mask: '(###)-####' },
    { code: '+246', id: CountryId.BRITISH_INDIAN_OCEAN_TERRITORY, flag: '🇮🇴', name: 'British Indian Ocean Territory', mask: '(###)-####' },
    { code: '+247', id: CountryId.ASCENSION_ISLAND, flag: '🇦🇨', name: 'Ascension Island', mask: '####' },
    { code: '+248', id: CountryId.SEYCHELLES, flag: '🇸🇨', name: 'Seychelles', mask: '(#)-###-###' },
    { code: '+249', id: CountryId.SUDAN, flag: '🇸🇩', name: 'Sudan', mask: '(##)-###-####' },
    { code: '+250', id: CountryId.RWANDA, flag: '🇷🇼', name: 'Rwanda', mask: '(###)-###-###' },
    { code: '+251', id: CountryId.ETHIOPIA, flag: '🇪🇹', name: 'Ethiopia', mask: '(##)-###-####' },
    { code: '+252', id: CountryId.SOMALIA, flag: '🇸🇴', name: 'Somalia', mask: '(##)-###-####' },
    { code: '+253', id: CountryId.DJIBOUTI, flag: '🇩🇯', name: 'Djibouti', mask: '(##)-##-##-##' },
    { code: '+254', id: CountryId.KENYA, flag: '🇰🇪', name: 'Kenya', mask: '(###)-######' },
    { code: '+255', id: CountryId.TANZANIA, flag: '🇹🇿', name: 'Tanzania', mask: '(###)-###-###' },
    { code: '+256', id: CountryId.UGANDA, flag: '🇺🇬', name: 'Uganda', mask: '(###)-######' },
    { code: '+257', id: CountryId.BURUNDI, flag: '🇧🇮', name: 'Burundi', mask: '(##)-##-##-##' },
    { code: '+258', id: CountryId.MOZAMBIQUE, flag: '🇲🇿', name: 'Mozambique', mask: '(##)-###-####' },
    { code: '+260', id: CountryId.ZAMBIA, flag: '🇿🇲', name: 'Zambia', mask: '(##)-###-####' },
    { code: '+261', id: CountryId.MADAGASCAR, flag: '🇲🇬', name: 'Madagascar', mask: '(##)-##-###-##' },
    { code: '+262', id: CountryId.REUNION, flag: '🇷🇪', name: 'Réunion', mask: '(###)-##-##-##' },
    { code: '+262', id: CountryId.MAYOTTE, flag: '🇾🇹', name: 'Mayotte', mask: '(###)-##-##-##' },
    { code: '+263', id: CountryId.ZIMBABWE, flag: '🇿🇼', name: 'Zimbabwe', mask: '(##)-###-####' },
    { code: '+264', id: CountryId.NAMIBIA, flag: '🇳🇦', name: 'Namibia', mask: '(##)-###-####' },
    { code: '+265', id: CountryId.MALAWI, flag: '🇲🇼', name: 'Malawi', mask: '(###)-##-##-##' },
    { code: '+266', id: CountryId.LESOTHO, flag: '🇱🇸', name: 'Lesotho', mask: '(##)-###-###' },
    { code: '+267', id: CountryId.BOTSWANA, flag: '🇧🇼', name: 'Botswana', mask: '(##)-###-###' },
    { code: '+268', id: CountryId.ESWATINI, flag: '🇸🇿', name: 'Eswatini', mask: '(##)-##-####' },
    { code: '+269', id: CountryId.COMOROS, flag: '🇰🇲', name: 'Comoros', mask: '(###)-##-##' },
    { code: '+27', id: CountryId.SOUTH_AFRICA, flag: '🇿🇦', name: 'South Africa', mask: '(##)-###-####' },
    { code: '+290', id: CountryId.SAINT_HELENA, flag: '🇸🇭', name: 'Saint Helena', mask: '#####' },
    { code: '+291', id: CountryId.ERITREA, flag: '🇪🇷', name: 'Eritrea', mask: '(#)-###-###' },
    { code: '+297', id: CountryId.ARUBA, flag: '🇦🇼', name: 'Aruba', mask: '(###)-####' },
    { code: '+298', id: CountryId.FAROE_ISLANDS, flag: '🇫🇴', name: 'Faroe Islands', mask: '(###)-###' },
    { code: '+299', id: CountryId.GREENLAND, flag: '🇬🇱', name: 'Greenland', mask: '(##)-##-##' },
    // Zone 3 - Europe
    { code: '+30', id: CountryId.GREECE, flag: '🇬🇷', name: 'Greece', mask: '(###)-###-####' },
    { code: '+31', id: CountryId.NETHERLANDS, flag: '🇳🇱', name: 'Netherlands', mask: '(##)-###-####' },
    { code: '+32', id: CountryId.BELGIUM, flag: '🇧🇪', name: 'Belgium', mask: '(###)-##-##-##' },
    { code: '+33', id: CountryId.FRANCE, flag: '🇫🇷', name: 'France', mask: '(#)-##-##-##-##' },
    { code: '+34', id: CountryId.SPAIN, flag: '🇪🇸', name: 'Spain', mask: '(###)-###-###' },
    { code: '+350', id: CountryId.GIBRALTAR, flag: '🇬🇮', name: 'Gibraltar', mask: '#####' },
    { code: '+351', id: CountryId.PORTUGAL, flag: '🇵🇹', name: 'Portugal', mask: '(###)-###-###' },
    { code: '+352', id: CountryId.LUXEMBOURG, flag: '🇱🇺', name: 'Luxembourg', mask: '(###)-###-###' },
    { code: '+353', id: CountryId.IRELAND, flag: '🇮🇪', name: 'Ireland', mask: '(##)-###-####' },
    { code: '+354', id: CountryId.ICELAND, flag: '🇮🇸', name: 'Iceland', mask: '(###)-####' },
    { code: '+355', id: CountryId.ALBANIA, flag: '🇦🇱', name: 'Albania', mask: '(###)-###-###' },
    { code: '+356', id: CountryId.MALTA, flag: '🇲🇹', name: 'Malta', mask: '(####)-####' },
    { code: '+357', id: CountryId.CYPRUS, flag: '🇨🇾', name: 'Cyprus', mask: '(##)-######' },
    { code: '+358', id: CountryId.FINLAND, flag: '🇫🇮', name: 'Finland', mask: '(##)-###-##-##' },
    { code: '+358', id: CountryId.ALAND_ISLANDS, flag: '🇦🇽', name: 'Åland Islands', mask: '(##)-###-##-##' },
    { code: '+359', id: CountryId.BULGARIA, flag: '🇧🇬', name: 'Bulgaria', mask: '(##)-###-####' },
    { code: '+36', id: CountryId.HUNGARY, flag: '🇭🇺', name: 'Hungary', mask: '(##)-###-####' },
    { code: '+370', id: CountryId.LITHUANIA, flag: '🇱🇹', name: 'Lithuania', mask: '(###)-##-###' },
    { code: '+371', id: CountryId.LATVIA, flag: '🇱🇻', name: 'Latvia', mask: '(##)-###-###' },
    { code: '+372', id: CountryId.ESTONIA, flag: '🇪🇪', name: 'Estonia', mask: '(##)-###-###' },
    { code: '+373', id: CountryId.MOLDOVA, flag: '🇲🇩', name: 'Moldova', mask: '(##)-###-###' },
    { code: '+374', id: CountryId.ARMENIA, flag: '🇦🇲', name: 'Armenia', mask: '(##)-###-###' },
    { code: '+375', id: CountryId.BELARUS, flag: '🇧🇾', name: 'Belarus', mask: '(##)-###-##-##' },
    { code: '+376', id: CountryId.ANDORRA, flag: '🇦🇩', name: 'Andorra', mask: '(###)-###' },
    { code: '+377', id: CountryId.MONACO, flag: '🇲🇨', name: 'Monaco', mask: '(##)-##-##-##' },
    { code: '+378', id: CountryId.SAN_MARINO, flag: '🇸🇲', name: 'San Marino', mask: '(####)-######' },
    { code: '+380', id: CountryId.UKRAINE, flag: '🇺🇦', name: 'Ukraine', mask: '(##)-###-##-##' },
    { code: '+381', id: CountryId.SERBIA, flag: '🇷🇸', name: 'Serbia', mask: '(##)-###-####' },
    { code: '+382', id: CountryId.MONTENEGRO, flag: '🇲🇪', name: 'Montenegro', mask: '(##)-###-###' },
    { code: '+383', id: CountryId.KOSOVO, flag: '🇽🇰', name: 'Kosovo', mask: '(##)-###-###' },
    { code: '+385', id: CountryId.CROATIA, flag: '🇭🇷', name: 'Croatia', mask: '(##)-###-###' },
    { code: '+386', id: CountryId.SLOVENIA, flag: '🇸🇮', name: 'Slovenia', mask: '(##)-###-###' },
    { code: '+387', id: CountryId.BOSNIA_AND_HERZEGOVINA, flag: '🇧🇦', name: 'Bosnia and Herzegovina', mask: '(##)-###-###' },
    { code: '+389', id: CountryId.NORTH_MACEDONIA, flag: '🇲🇰', name: 'North Macedonia', mask: '(##)-###-###' },
    { code: '+39', id: CountryId.ITALY, flag: '🇮🇹', name: 'Italy', mask: '(###)-###-####' },
    { code: '+39', id: CountryId.VATICAN_CITY, flag: '🇻🇦', name: 'Vatican City', mask: '(##)-####-####' },
    { code: '+40', id: CountryId.ROMANIA, flag: '🇷🇴', name: 'Romania', mask: '(###)-###-###' },
    { code: '+41', id: CountryId.SWITZERLAND, flag: '🇨🇭', name: 'Switzerland', mask: '(##)-###-##-##' },
    { code: '+420', id: CountryId.CZECH_REPUBLIC, flag: '🇨🇿', name: 'Czech Republic', mask: '(###)-###-###' },
    { code: '+421', id: CountryId.SLOVAKIA, flag: '🇸🇰', name: 'Slovakia', mask: '(###)-###-###' },
    { code: '+423', id: CountryId.LIECHTENSTEIN, flag: '🇱🇮', name: 'Liechtenstein', mask: '(###)-####' },
    { code: '+43', id: CountryId.AUSTRIA, flag: '🇦🇹', name: 'Austria', mask: '(###)-###-####' },
    { code: '+44', id: CountryId.UNITED_KINGDOM, flag: '🇬🇧', name: 'United Kingdom', mask: '(####)-######' },
    { code: '+44', id: CountryId.GUERNSEY, flag: '🇬🇬', name: 'Guernsey', mask: '(####)-######' },
    { code: '+44', id: CountryId.ISLE_OF_MAN, flag: '🇮🇲', name: 'Isle of Man', mask: '(####)-######' },
    { code: '+44', id: CountryId.JERSEY, flag: '🇯🇪', name: 'Jersey', mask: '(####)-######' },
    { code: '+45', id: CountryId.DENMARK, flag: '🇩🇰', name: 'Denmark', mask: '(##)-##-##-##' },
    { code: '+46', id: CountryId.SWEDEN, flag: '🇸🇪', name: 'Sweden', mask: '(##)-###-##-##' },
    { code: '+47', id: CountryId.NORWAY, flag: '🇳🇴', name: 'Norway', mask: '(###)-##-###' },
    { code: '+47', id: CountryId.SVALBARD_AND_JAN_MAYEN, flag: '🇸🇯', name: 'Svalbard and Jan Mayen', mask: '(###)-##-###' },
    { code: '+48', id: CountryId.POLAND, flag: '🇵🇱', name: 'Poland', mask: '(###)-###-###' },
    { code: '+49', id: CountryId.GERMANY, flag: '🇩🇪', name: 'Germany', mask: '(###)-#######' },
    // Zone 5 - Central & South America, Caribbean
    { code: '+500', id: CountryId.FALKLAND_ISLANDS, flag: '🇫🇰', name: 'Falkland Islands', mask: '#####' },
    { code: '+500', id: CountryId.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS, flag: '🇬🇸', name: 'South Georgia and the South Sandwich Islands', mask: '#####' },
    { code: '+501', id: CountryId.BELIZE, flag: '🇧🇿', name: 'Belize', mask: '(###)-####' },
    { code: '+502', id: CountryId.GUATEMALA, flag: '🇬🇹', name: 'Guatemala', mask: '(####)-####' },
    { code: '+503', id: CountryId.EL_SALVADOR, flag: '🇸🇻', name: 'El Salvador', mask: '(####)-####' },
    { code: '+504', id: CountryId.HONDURAS, flag: '🇭🇳', name: 'Honduras', mask: '(####)-####' },
    { code: '+505', id: CountryId.NICARAGUA, flag: '🇳🇮', name: 'Nicaragua', mask: '(####)-####' },
    { code: '+506', id: CountryId.COSTA_RICA, flag: '🇨🇷', name: 'Costa Rica', mask: '(####)-####' },
    { code: '+507', id: CountryId.PANAMA, flag: '🇵🇦', name: 'Panama', mask: '(####)-####' },
    { code: '+508', id: CountryId.SAINT_PIERRE_AND_MIQUELON, flag: '🇵🇲', name: 'Saint Pierre and Miquelon', mask: '(##)-##-##' },
    { code: '+509', id: CountryId.HAITI, flag: '🇭🇹', name: 'Haiti', mask: '(##)-##-####' },
    { code: '+51', id: CountryId.PERU, flag: '🇵🇪', name: 'Peru', mask: '(###)-###-###' },
    { code: '+52', id: CountryId.MEXICO, flag: '🇲🇽', name: 'Mexico', mask: '(##)-####-####' },
    { code: '+53', id: CountryId.CUBA, flag: '🇨🇺', name: 'Cuba', mask: '(#)-###-####' },
    { code: '+54', id: CountryId.ARGENTINA, flag: '🇦🇷', name: 'Argentina', mask: '(##)-####-####' },
    { code: '+55', id: CountryId.BRAZIL, flag: '🇧🇷', name: 'Brazil', mask: '(##)-#####-####' },
    { code: '+56', id: CountryId.CHILE, flag: '🇨🇱', name: 'Chile', mask: '(#)-####-####' },
    { code: '+57', id: CountryId.COLOMBIA, flag: '🇨🇴', name: 'Colombia', mask: '(###)-###-####' },
    { code: '+58', id: CountryId.VENEZUELA, flag: '🇻🇪', name: 'Venezuela', mask: '(###)-###-####' },
    { code: '+590', id: CountryId.GUADELOUPE, flag: '🇬🇵', name: 'Guadeloupe', mask: '(###)-##-##-##' },
    { code: '+590', id: CountryId.SAINT_BARTHELEMY, flag: '🇧🇱', name: 'Saint Barthélemy', mask: '(###)-##-##-##' },
    { code: '+590', id: CountryId.SAINT_MARTIN, flag: '🇲🇫', name: 'Saint Martin', mask: '(###)-##-##-##' },
    { code: '+591', id: CountryId.BOLIVIA, flag: '🇧🇴', name: 'Bolivia', mask: '(#)-###-####' },
    { code: '+592', id: CountryId.GUYANA, flag: '🇬🇾', name: 'Guyana', mask: '(###)-####' },
    { code: '+593', id: CountryId.ECUADOR, flag: '🇪🇨', name: 'Ecuador', mask: '(##)-###-####' },
    { code: '+594', id: CountryId.FRENCH_GUIANA, flag: '🇬🇫', name: 'French Guiana', mask: '(###)-##-##-##' },
    { code: '+595', id: CountryId.PARAGUAY, flag: '🇵🇾', name: 'Paraguay', mask: '(###)-###-###' },
    { code: '+596', id: CountryId.MARTINIQUE, flag: '🇲🇶', name: 'Martinique', mask: '(###)-##-##-##' },
    { code: '+597', id: CountryId.SURINAME, flag: '🇸🇷', name: 'Suriname', mask: '(###)-####' },
    { code: '+598', id: CountryId.URUGUAY, flag: '🇺🇾', name: 'Uruguay', mask: '(#)-###-##-##' },
    { code: '+599', id: CountryId.CURACAO, flag: '🇨🇼', name: 'Curaçao', mask: '(###)-####' },
    { code: '+599', id: CountryId.CARIBBEAN_NETHERLANDS, flag: '🇧🇶', name: 'Caribbean Netherlands', mask: '(###)-####' },
    // Zone 6 - Southeast Asia & Oceania
    { code: '+60', id: CountryId.MALAYSIA, flag: '🇲🇾', name: 'Malaysia', mask: '(##)-####-####' },
    { code: '+61', id: CountryId.AUSTRALIA, flag: '🇦🇺', name: 'Australia', mask: '(###)-###-###' },
    { code: '+61', id: CountryId.CHRISTMAS_ISLAND, flag: '🇨🇽', name: 'Christmas Island', mask: '(###)-###-###' },
    { code: '+61', id: CountryId.COCOS_KEELING_ISLANDS, flag: '🇨🇨', name: 'Cocos (Keeling) Islands', mask: '(###)-###-###' },
    { code: '+62', id: CountryId.INDONESIA, flag: '🇮🇩', name: 'Indonesia', mask: '(###)-####-####' },
    { code: '+63', id: CountryId.PHILIPPINES, flag: '🇵🇭', name: 'Philippines', mask: '(###)-###-####' },
    { code: '+64', id: CountryId.NEW_ZEALAND, flag: '🇳🇿', name: 'New Zealand', mask: '(##)-###-####' },
    { code: '+64', id: CountryId.PITCAIRN_ISLANDS, flag: '🇵🇳', name: 'Pitcairn Islands', mask: '(####)-####' },
    { code: '+65', id: CountryId.SINGAPORE, flag: '🇸🇬', name: 'Singapore', mask: '(####)-####' },
    { code: '+66', id: CountryId.THAILAND, flag: '🇹🇭', name: 'Thailand', mask: '(##)-###-####' },
    { code: '+670', id: CountryId.TIMOR_LESTE, flag: '🇹🇱', name: 'Timor-Leste', mask: '(###)-####' },
    { code: '+672', id: CountryId.NORFOLK_ISLAND, flag: '🇳🇫', name: 'Norfolk Island', mask: '(##)-####' },
    { code: '+673', id: CountryId.BRUNEI, flag: '🇧🇳', name: 'Brunei', mask: '(###)-####' },
    { code: '+674', id: CountryId.NAURU, flag: '🇳🇷', name: 'Nauru', mask: '(###)-####' },
    { code: '+675', id: CountryId.PAPUA_NEW_GUINEA, flag: '🇵🇬', name: 'Papua New Guinea', mask: '(##)-###-###' },
    { code: '+676', id: CountryId.TONGA, flag: '🇹🇴', name: 'Tonga', mask: '(###)-####' },
    { code: '+677', id: CountryId.SOLOMON_ISLANDS, flag: '🇸🇧', name: 'Solomon Islands', mask: '(###)-####' },
    { code: '+678', id: CountryId.VANUATU, flag: '🇻🇺', name: 'Vanuatu', mask: '(###)-####' },
    { code: '+679', id: CountryId.FIJI, flag: '🇫🇯', name: 'Fiji', mask: '(###)-####' },
    { code: '+680', id: CountryId.PALAU, flag: '🇵🇼', name: 'Palau', mask: '(###)-####' },
    { code: '+681', id: CountryId.WALLIS_AND_FUTUNA, flag: '🇼🇫', name: 'Wallis and Futuna', mask: '(##)-####' },
    { code: '+682', id: CountryId.COOK_ISLANDS, flag: '🇨🇰', name: 'Cook Islands', mask: '(##)-###' },
    { code: '+683', id: CountryId.NIUE, flag: '🇳🇺', name: 'Niue', mask: '####' },
    { code: '+685', id: CountryId.SAMOA, flag: '🇼🇸', name: 'Samoa', mask: '(##)-#####' },
    { code: '+686', id: CountryId.KIRIBATI, flag: '🇰🇮', name: 'Kiribati', mask: '(##)-##-###' },
    { code: '+687', id: CountryId.NEW_CALEDONIA, flag: '🇳🇨', name: 'New Caledonia', mask: '(##)-##-##' },
    { code: '+688', id: CountryId.TUVALU, flag: '🇹🇻', name: 'Tuvalu', mask: '(##)-###' },
    { code: '+689', id: CountryId.FRENCH_POLYNESIA, flag: '🇵🇫', name: 'French Polynesia', mask: '(##)-##-##-##' },
    { code: '+690', id: CountryId.TOKELAU, flag: '🇹🇰', name: 'Tokelau', mask: '####' },
    { code: '+691', id: CountryId.MICRONESIA, flag: '🇫🇲', name: 'Micronesia', mask: '(###)-####' },
    { code: '+692', id: CountryId.MARSHALL_ISLANDS, flag: '🇲🇭', name: 'Marshall Islands', mask: '(###)-####' },
    // Zone 7 - Russia & Kazakhstan
    { code: '+7', id: CountryId.RUSSIA, flag: '🇷🇺', name: 'Russia', mask: '(###)-###-##-##' },
    { code: '+7', id: CountryId.KAZAKHSTAN, flag: '🇰🇿', name: 'Kazakhstan', mask: '(###)-###-##-##' },
    // Zone 8 - East Asia
    { code: '+81', id: CountryId.JAPAN, flag: '🇯🇵', name: 'Japan', mask: '(##)-####-####' },
    { code: '+82', id: CountryId.SOUTH_KOREA, flag: '🇰🇷', name: 'South Korea', mask: '(##)-####-####' },
    { code: '+84', id: CountryId.VIETNAM, flag: '🇻🇳', name: 'Vietnam', mask: '(###)-###-####' },
    { code: '+850', id: CountryId.NORTH_KOREA, flag: '🇰🇵', name: 'North Korea', mask: '(###)-###-####' },
    { code: '+852', id: CountryId.HONG_KONG, flag: '🇭🇰', name: 'Hong Kong', mask: '(####)-####' },
    { code: '+853', id: CountryId.MACAU, flag: '🇲🇴', name: 'Macau', mask: '(####)-####' },
    { code: '+855', id: CountryId.CAMBODIA, flag: '🇰🇭', name: 'Cambodia', mask: '(##)-###-###' },
    { code: '+856', id: CountryId.LAOS, flag: '🇱🇦', name: 'Laos', mask: '(##)-###-####' },
    { code: '+86', id: CountryId.CHINA, flag: '🇨🇳', name: 'China', mask: '(###)-####-####' },
    { code: '+880', id: CountryId.BANGLADESH, flag: '🇧🇩', name: 'Bangladesh', mask: '(##)-####-####' },
    { code: '+886', id: CountryId.TAIWAN, flag: '🇹🇼', name: 'Taiwan', mask: '(###)-###-####' },
    // Zone 9 - South Asia, Middle East & Central Asia
    { code: '+90', id: CountryId.TURKEY, flag: '🇹🇷', name: 'Turkey', mask: '(###)-###-##-##' },
    { code: '+91', id: CountryId.INDIA, flag: '🇮🇳', name: 'India', mask: '(#####)-#####' },
    { code: '+92', id: CountryId.PAKISTAN, flag: '🇵🇰', name: 'Pakistan', mask: '(###)-###-####' },
    { code: '+93', id: CountryId.AFGHANISTAN, flag: '🇦🇫', name: 'Afghanistan', mask: '(##)-###-####' },
    { code: '+94', id: CountryId.SRI_LANKA, flag: '🇱🇰', name: 'Sri Lanka', mask: '(##)-###-####' },
    { code: '+95', id: CountryId.MYANMAR, flag: '🇲🇲', name: 'Myanmar', mask: '(##)-###-####' },
    { code: '+960', id: CountryId.MALDIVES, flag: '🇲🇻', name: 'Maldives', mask: '(###)-####' },
    { code: '+961', id: CountryId.LEBANON, flag: '🇱🇧', name: 'Lebanon', mask: '(##)-###-###' },
    { code: '+962', id: CountryId.JORDAN, flag: '🇯🇴', name: 'Jordan', mask: '(##)-###-####' },
    { code: '+963', id: CountryId.SYRIA, flag: '🇸🇾', name: 'Syria', mask: '(###)-###-###' },
    { code: '+964', id: CountryId.IRAQ, flag: '🇮🇶', name: 'Iraq', mask: '(###)-###-####' },
    { code: '+965', id: CountryId.KUWAIT, flag: '🇰🇼', name: 'Kuwait', mask: '(####)-####' },
    { code: '+966', id: CountryId.SAUDI_ARABIA, flag: '🇸🇦', name: 'Saudi Arabia', mask: '(##)-###-####' },
    { code: '+967', id: CountryId.YEMEN, flag: '🇾🇪', name: 'Yemen', mask: '(###)-###-###' },
    { code: '+968', id: CountryId.OMAN, flag: '🇴🇲', name: 'Oman', mask: '(####)-####' },
    { code: '+970', id: CountryId.PALESTINIAN_TERRITORIES, flag: '🇵🇸', name: 'Palestinian Territories', mask: '(##)-###-####' },
    { code: '+971', id: CountryId.UNITED_ARAB_EMIRATES, flag: '🇦🇪', name: 'United Arab Emirates', mask: '(##)-###-####' },
    { code: '+972', id: CountryId.ISRAEL, flag: '🇮🇱', name: 'Israel', mask: '(##)-###-####' },
    { code: '+973', id: CountryId.BAHRAIN, flag: '🇧🇭', name: 'Bahrain', mask: '(####)-####' },
    { code: '+974', id: CountryId.QATAR, flag: '🇶🇦', name: 'Qatar', mask: '(####)-####' },
    { code: '+975', id: CountryId.BHUTAN, flag: '🇧🇹', name: 'Bhutan', mask: '(##)-###-###' },
    { code: '+976', id: CountryId.MONGOLIA, flag: '🇲🇳', name: 'Mongolia', mask: '(####)-####' },
    { code: '+977', id: CountryId.NEPAL, flag: '🇳🇵', name: 'Nepal', mask: '(##)-###-####' },
    { code: '+98', id: CountryId.IRAN, flag: '🇮🇷', name: 'Iran', mask: '(###)-###-####' },
    { code: '+992', id: CountryId.TAJIKISTAN, flag: '🇹🇯', name: 'Tajikistan', mask: '(##)-###-####' },
    { code: '+993', id: CountryId.TURKMENISTAN, flag: '🇹🇲', name: 'Turkmenistan', mask: '(##)-###-####' },
    { code: '+994', id: CountryId.AZERBAIJAN, flag: '🇦🇿', name: 'Azerbaijan', mask: '(##)-###-##-##' },
    { code: '+995', id: CountryId.GEORGIA, flag: '🇬🇪', name: 'Georgia', mask: '(###)-###-###' },
    { code: '+996', id: CountryId.KYRGYZSTAN, flag: '🇰🇬', name: 'Kyrgyzstan', mask: '(###)-###-###' },
    { code: '+998', id: CountryId.UZBEKISTAN, flag: '🇺🇿', name: 'Uzbekistan', mask: '(##)-###-##-##' },
];
